version: "3"

services: 
  arm:
    # コンテナ名を指定して docker exec が楽
    container_name: arm
    
    # Dockerfile の場所
    build: .

    # ホストOSのボリュームをコンテナOSとマウント
    volumes: 
      - ./src:/work/src

    # docker-compose up したときにコンテナが終了しないよう永続化
    tty: true
